language: python

python:
- 3.6
install:
- pip install -r requirements.txt
- pip install codeclimate-test-reporter

script:
- pytest --cov-report term-missing --cov=application
- coveralls

after_success:
- coveralls
- codeclimate-test-reporter
